version: '3.7'

services:
  mirth:
    image: michaelleehobbs/mirth:3.7.1.b243-v0.3.0
    volumes:
      - /efs/volumes/mirth/appdata:/opt/mirthconnect/appdata
      - /efs/volumes/mirth/conf:/opt/mirthconnect/conf
    ports:
      - "80:8080"
      - "443:8443"
      - "5000:5000"
    env_file: .env.mirth.aws.prod
